### ISSUE TITLE
Error whenever I try to expand the ShopifyAuthenticators tree 

### ISSUE THREAD

**Issue by nick-groupe-ratte** [TorqIT/store-syndicator-bundle#73]
Message: encrypted field APIAccessToken cannot be decoded
Trace: 
in /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/EncryptedField.php:185

**Comment by nick-groupe-ratte** [comment]
@cameronfromtorq

**Comment by evanjamesjackson** [comment]
@nick-groupe-ratte Hi Nick - are you experiencing this locally or in the dev site?

**Comment by nick-groupe-ratte** [comment]
@evanjamesjackson Locally

**Comment by nick-groupe-ratte** [comment]
And I should add that I am using a database export from the dev site from yesterday.

**Comment by cameronfromtorq** [comment]
@nick-groupe-ratte 
Thanks for reaching out Nick, i believe this is the cause of your issue:
This bundle uses pimcore's encrypted data type to store the shopify credentials: https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/Others/#encrypted-field

this is causing an issue because we have different encryption secrets between local and dev environments. Because of this, you will need to delete the shopifyauthenticator object that was included in the database export and remake it. make sure to point the shopify export config to the new object you made.

**Comment by nick-groupe-ratte** [comment]
Hello @cameronfromtorq,

Ahh ok that makes sense. 
I plan on importing the DB from the dev site to my local environment frequently. Do you think it would be okay for me to share the same encryption keys?

**Comment by cameronfromtorq** [comment]
@nick-groupe-ratte I would recommend against sharing an encryption key between local and dev environments as it will increase the risk of leaking your shopify credentials if someone gains access to your dev database.

**Comment by nick-groupe-ratte** [comment]
Hello @cameronfromtorq  I asked Francis and he agrees with me that the risk acceptable. Could you show me how to access the file in the root of the project so I can copy the key in the .env file? In the console I can only access the files under pimcore-root

**Comment by cameronfromtorq** [comment]
@nick-groupe-ratte we have this key being injected into the container via an env variable called ENCRYPTION_SECRET. If you bash into the dev container and `printenv ENCRYPTION_SECRET` you will get the secret present on dev. 

I would highly advise you to not commit this in your github repo though. Maybe set up a .gitignore for the .env file.

**Comment by nick-groupe-ratte** [comment]
@cameronfromtorq Thank you.
yes I agree, i wont commit the .env file
